# Cloud Build pipeline for deploying the backend (in ./backend) to Cloud Run
# Requires an Artifact Registry repo and a Secret Manager secret named POSTGRES_URL

substitutions:
  _REGION: asia-southeast1                 # pick your region
  _SERVICE: myvault-api                    # Cloud Run service name
  _REPO: myvault-backend                   # Artifact Registry repo name
  _SERVICE_ACCOUNT: myvault-runner@$PROJECT_ID.iam.gserviceaccount.com
  _IMAGE: $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/myvault-backend

steps:
  # Build the backend image from the ./backend directory
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "$_IMAGE:$SHORT_SHA", "backend"]

  # Push image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "$_IMAGE:$SHORT_SHA"]

  # Deploy to Cloud Run with DATABASE_URL from Secret Manager
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","$_SERVICE",
        "--image","$_IMAGE:$SHORT_SHA",
        "--region","$_REGION",
        "--allow-unauthenticated",
        "--platform","managed",
        "--service-account","$_SERVICE_ACCOUNT",
        "--set-secrets","DATABASE_URL=projects/$PROJECT_ID/secrets/POSTGRES_URL/versions/latest",
        "--update-env-vars","ENV=prod,DB_POOL_CLASS=null,PROD_FRONTEND_ORIGIN=https://<frontend-domain>",
        "--update-env-vars","PYTHONUNBUFFERED=1",
        "--concurrency","10",
        "--max-instances","5"
      ]

images:
  - "$_IMAGE:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
