# Cloud Build pipeline for deploying both frontend and backend to Cloud Run
# Requires Artifact Registry repos and proper service account setup

steps:
  # Build backend (UNCHANGED)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/myvault-backend', '-f', './backend/Dockerfile', './backend']

  # Build frontend with caching (MODIFIED)
  # CHANGE: Added caching by pulling previous image and using --cache-from to reuse layers
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t gcr.io/$PROJECT_ID/myvault-frontend \
          --build-arg VITE_API_URL=https://myvault-api-$PROJECT_ID.asia-southeast1.run.app/api \
          --build-arg VITE_GOOGLE_CLOUD_PROJECT=$PROJECT_ID \
          -f ./frontend/Dockerfile \
          ./frontend
    id: 'build-frontend'
    volumes:
      - name: 'npm-cache'
        path: '/npm-cache'

  # Push images (UNCHANGED)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/myvault-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/myvault-frontend']

  # Deploy backend (UNCHANGED)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'myvault-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/myvault-backend'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENV=production,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,PROD_FRONTEND_ORIGIN=https://myvault-web-$PROJECT_ID.asia-southeast1.run.app'
      - '--concurrency'
      - '10'
      - '--max-instances'
      - '5'

  # Deploy frontend with no-traffic option (MODIFIED)
  # CHANGE: Added --no-traffic to deploy without shifting traffic immediately
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'myvault-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/myvault-frontend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast1'
      - '--allow-unauthenticated'
      - '--no-traffic'  # CHANGE: Deploy new revision without traffic shift
      - '--set-env-vars'
      - 'VITE_API_URL=https://myvault-api-$PROJECT_ID.asia-southeast1.run.app/api,VITE_GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
      - '--concurrency'
      - '80'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'  # CHANGE: Added ID for clarity

  # Shift traffic to the new frontend revision (ADDED)
  # CHANGE: Added step to update traffic after deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'myvault-web'
      - '--to-latest'
      - '--region'
      - 'asia-southeast1'
    id: 'update-traffic-frontend'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/myvault-backend'
  - 'gcr.io/$PROJECT_ID/myvault-frontend'
