# Google Cloud Build configuration for deploying to Cloud Run
steps:
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/myvault-backend:$BUILD_ID'
      - './backend'

  # Build Frontend Image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/myvault-frontend:$BUILD_ID'
      - './frontend'

  # Push Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/myvault-backend:$BUILD_ID'

  # Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/myvault-frontend:$BUILD_ID'

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'myvault-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/myvault-backend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENV=production,DATABASE_URL=sqlite:///./data/myvault.db'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'

  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'myvault-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/myvault-frontend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'VITE_API_URL=https://myvault-backend-[PROJECT-HASH]-uc.a.run.app/api'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/myvault-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/myvault-frontend:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
